<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MeatProduct;
use Illuminate\Support\Facades\DB;

class MeatProductsSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // لحمة بقر
            [
                'name' => 'لحمة بقر',
                'description' => 'لحمة بقر طازجة عالية الجودة',
                'current_stock' => 50.5,
                'cost_price' => 12.5,
                'selling_price' => 18.0,
                'waste_percentage' => 8.0,
                'is_active' => true,
            ],
            [
                'name' => 'فيليه عجل',
                'description' => 'فيليه عجل مفروم طازج',
                'current_stock' => 25.0,
                'cost_price' => 15.0,
                'selling_price' => 22.0,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'برغر',
                'description' => 'برغر لحم بقر طازج',
                'current_stock' => 30.0,
                'cost_price' => 8.5,
                'selling_price' => 12.0,
                'waste_percentage' => 3.0,
                'is_active' => true,
            ],
            [
                'name' => 'كفتة',
                'description' => 'كفتة لحم متبلة',
                'current_stock' => 18.5,
                'cost_price' => 9.0,
                'selling_price' => 13.5,
                'waste_percentage' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'كبة غنم',
                'description' => 'كبة لحم غنم',
                'current_stock' => 15.0,
                'cost_price' => 11.0,
                'selling_price' => 16.0,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            // دجاج
            [
                'name' => 'سودة دجاج',
                'description' => 'صدر دجاج بدون عظم',
                'current_stock' => 40.0,
                'cost_price' => 6.5,
                'selling_price' => 9.5,
                'waste_percentage' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'طاووق أبيض',
                'description' => 'دجاج طاووق تتبيلة بيضاء',
                'current_stock' => 22.0,
                'cost_price' => 7.0,
                'selling_price' => 10.5,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'طاووق أحمر',
                'description' => 'دجاج طاووق تتبيلة حمراء',
                'current_stock' => 20.0,
                'cost_price' => 7.2,
                'selling_price' => 10.8,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'فاهيتا دجاج',
                'description' => 'شرائح دجاج للفاهيتا',
                'current_stock' => 18.0,
                'cost_price' => 6.8,
                'selling_price' => 10.0,
                'waste_percentage' => 4.5,
                'is_active' => true,
            ],
            // لحمة غنم
            [
                'name' => 'بقر عرض',
                'description' => 'لحمة بقر للعرض',
                'current_stock' => 35.0,
                'cost_price' => 13.0,
                'selling_price' => 19.0,
                'waste_percentage' => 9.0,
                'is_active' => true,
            ],
            [
                'name' => 'جيكو غنم',
                'description' => 'قطع غنم جيكو',
                'current_stock' => 28.0,
                'cost_price' => 16.0,
                'selling_price' => 23.0,
                'waste_percentage' => 7.0,
                'is_active' => true,
            ],
            [
                'name' => 'فيليه غنم',
                'description' => 'فيليه غنم طري',
                'current_stock' => 15.0,
                'cost_price' => 18.0,
                'selling_price' => 26.0,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'عصعوص عجل',
                'description' => 'عصعوص عجل طازج',
                'current_stock' => 12.0,
                'cost_price' => 14.0,
                'selling_price' => 20.0,
                'waste_percentage' => 8.0,
                'is_active' => true,
            ],
            [
                'name' => 'نية مشكل',
                'description' => 'نية لحم مشكل',
                'current_stock' => 25.0,
                'cost_price' => 10.5,
                'selling_price' => 15.5,
                'waste_percentage' => 10.0,
                'is_active' => true,
            ],
            // منتجات دجاج متنوعة
            [
                'name' => 'جوانح متبل',
                'description' => 'جوانح دجاج متبلة',
                'current_stock' => 30.0,
                'cost_price' => 5.5,
                'selling_price' => 8.5,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'ناغتس',
                'description' => 'ناغتس دجاج',
                'current_stock' => 45.0,
                'cost_price' => 4.5,
                'selling_price' => 7.0,
                'waste_percentage' => 2.0,
                'is_active' => true,
            ],
            [
                'name' => 'كوردن بلو دجاج',
                'description' => 'كوردن بلو بالدجاج',
                'current_stock' => 20.0,
                'cost_price' => 8.0,
                'selling_price' => 12.0,
                'waste_percentage' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'اسكالوب',
                'description' => 'اسكالوب دجاج',
                'current_stock' => 18.0,
                'cost_price' => 7.5,
                'selling_price' => 11.0,
                'waste_percentage' => 4.5,
                'is_active' => true,
            ],
            [
                'name' => 'كريسبي',
                'description' => 'دجاج كريسبي',
                'current_stock' => 22.0,
                'cost_price' => 6.0,
                'selling_price' => 9.0,
                'waste_percentage' => 3.5,
                'is_active' => true,
            ],
            // لحمة غنم متنوعة
            [
                'name' => 'لية غنم',
                'description' => 'لية غنم طازجة',
                'current_stock' => 16.0,
                'cost_price' => 12.0,
                'selling_price' => 17.5,
                'waste_percentage' => 8.0,
                'is_active' => true,
            ],
            [
                'name' => 'كتف غنم',
                'description' => 'كتف غنم بدون عظم',
                'current_stock' => 24.0,
                'cost_price' => 14.5,
                'selling_price' => 21.0,
                'waste_percentage' => 7.0,
                'is_active' => true,
            ],
            [
                'name' => 'بيض عجل',
                'description' => 'بيض عجل طازج',
                'current_stock' => 10.0,
                'cost_price' => 9.0,
                'selling_price' => 13.5,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'معلاق غنم',
                'description' => 'معلاق غنم',
                'current_stock' => 14.0,
                'cost_price' => 11.5,
                'selling_price' => 16.5,
                'waste_percentage' => 9.0,
                'is_active' => true,
            ],
            // منتجات مصنعة
            [
                'name' => 'مقانق',
                'description' => 'مقانق لحم',
                'current_stock' => 35.0,
                'cost_price' => 5.0,
                'selling_price' => 7.5,
                'waste_percentage' => 3.0,
                'is_active' => true,
            ],
            [
                'name' => 'سجق',
                'description' => 'سجق لحم',
                'current_stock' => 28.0,
                'cost_price' => 4.8,
                'selling_price' => 7.2,
                'waste_percentage' => 3.0,
                'is_active' => true,
            ],
            [
                'name' => 'زور مفروم',
                'description' => 'زور لحم مفروم',
                'current_stock' => 20.0,
                'cost_price' => 8.5,
                'selling_price' => 12.5,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'كتف غنم بعظمه',
                'description' => 'كتف غنم مع العظم',
                'current_stock' => 18.0,
                'cost_price' => 10.0,
                'selling_price' => 14.5,
                'waste_percentage' => 12.0,
                'is_active' => true,
            ],
            // منتجات خاصة
            [
                'name' => 'موزات برازيلي',
                'description' => 'موزات لحم برازيلي',
                'current_stock' => 15.0,
                'cost_price' => 13.5,
                'selling_price' => 19.5,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'روستو حلبي',
                'description' => 'روستو على الطريقة الحلبية',
                'current_stock' => 12.0,
                'cost_price' => 9.5,
                'selling_price' => 14.0,
                'waste_percentage' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'تشكن برغر',
                'description' => 'برغر دجاج',
                'current_stock' => 25.0,
                'cost_price' => 6.5,
                'selling_price' => 9.5,
                'waste_percentage' => 3.0,
                'is_active' => true,
            ],
            [
                'name' => 'لسان عجل كامل',
                'description' => 'لسان عجل كامل',
                'current_stock' => 8.0,
                'cost_price' => 15.0,
                'selling_price' => 22.0,
                'waste_percentage' => 8.0,
                'is_active' => true,
            ],
            [
                'name' => 'لسان غنم',
                'description' => 'لسان غنم',
                'current_stock' => 10.0,
                'cost_price' => 12.0,
                'selling_price' => 18.0,
                'waste_percentage' => 7.0,
                'is_active' => true,
            ],
            // منتجات إضافية
            [
                'name' => 'سودة بقر',
                'description' => 'صدر بقر',
                'current_stock' => 22.0,
                'cost_price' => 14.0,
                'selling_price' => 20.5,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'كوردن بلو لحمة',
                'description' => 'كوردن بلو باللحمة',
                'current_stock' => 16.0,
                'cost_price' => 10.0,
                'selling_price' => 15.0,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'ورك دجاج',
                'description' => 'ورك دجاج',
                'current_stock' => 30.0,
                'cost_price' => 5.0,
                'selling_price' => 7.5,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'طحال بقر',
                'description' => 'طحال بقر',
                'current_stock' => 12.0,
                'cost_price' => 6.0,
                'selling_price' => 9.0,
                'waste_percentage' => 10.0,
                'is_active' => true,
            ],
            [
                'name' => 'كوتلات غنم',
                'description' => 'كوتلات غنم',
                'current_stock' => 20.0,
                'cost_price' => 13.0,
                'selling_price' => 19.0,
                'waste_percentage' => 7.0,
                'is_active' => true,
            ],
            [
                'name' => 'لسان بقر مفروم',
                'description' => 'لسان بقر مفروم',
                'current_stock' => 14.0,
                'cost_price' => 11.0,
                'selling_price' => 16.5,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'بفتاك شوي',
                'description' => 'بفتاك للشوي',
                'current_stock' => 18.0,
                'cost_price' => 9.5,
                'selling_price' => 14.0,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'نخاع غنم',
                'description' => 'نخاع غنم',
                'current_stock' => 6.0,
                'cost_price' => 8.0,
                'selling_price' => 12.0,
                'waste_percentage' => 12.0,
                'is_active' => true,
            ],
            [
                'name' => 'فخاد مسحب',
                'description' => 'فخاد دجاج مسحب',
                'current_stock' => 25.0,
                'cost_price' => 6.8,
                'selling_price' => 10.0,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'عصب بقر',
                'description' => 'عصب بقر',
                'current_stock' => 10.0,
                'cost_price' => 7.5,
                'selling_price' => 11.5,
                'waste_percentage' => 8.0,
                'is_active' => true,
            ],
            [
                'name' => 'فخاد',
                'description' => 'فخاد دجاج',
                'current_stock' => 35.0,
                'cost_price' => 5.5,
                'selling_price' => 8.5,
                'waste_percentage' => 6.0,
                'is_active' => true,
            ],
            [
                'name' => 'جوانح',
                'description' => 'جوانح دجاج',
                'current_stock' => 40.0,
                'cost_price' => 4.0,
                'selling_price' => 6.5,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'دبوس',
                'description' => 'دبوس دجاج',
                'current_stock' => 15.0,
                'cost_price' => 4.5,
                'selling_price' => 7.0,
                'waste_percentage' => 7.0,
                'is_active' => true,
            ],
            [
                'name' => 'صدور',
                'description' => 'صدور دجاج',
                'current_stock' => 45.0,
                'cost_price' => 7.0,
                'selling_price' => 10.5,
                'waste_percentage' => 4.0,
                'is_active' => true,
            ],
            [
                'name' => 'فروج',
                'description' => 'دجاج فروج',
                'current_stock' => 20.0,
                'cost_price' => 8.0,
                'selling_price' => 12.0,
                'waste_percentage' => 5.0,
                'is_active' => true,
            ],
            [
                'name' => 'سويلي',
                'description' => 'سويلي دجاج',
                'current_stock' => 18.0,
                'cost_price' => 6.5,
                'selling_price' => 9.8,
                'waste_percentage' => 4.5,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            MeatProduct::create($product);
        }

        $this->command->info('تم إضافة ' . count($products) . ' منتج لحوم بنجاح!');
    }
}
